name: image-captioning
channels:
- https://conda.anaconda.org/menpo
- defaults
- conda-forge
- anaconda
dependencies:
    - python==3.6
    - numpy
    - matplotlib
    - tensorflow-gpu
    - keras
    - scikit-learn
    - tqdm
    - pillow
    - pydot
    - pandas
    - pip:
        - opencv-contrib-python
        - mtranslate
